[versions]
sample-app = "0.0.2"
radio-sdk = "3.4.22"
kotlin = "1.9.23"
kotlinx-serialization = "1.7.0"

[libraries]
radioSdk = { module = "com.gotenna.sdk:radio-sdk-external-jvm", version.ref = "radio-sdk" }
kotlinx-serialization-protobuf-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf-jvm", version.ref = "kotlinx-serialization" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
