name: Slack Notification - Pull Request Opened

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  send_slack_message:
    uses: gotenna/gha-workflows/.github/workflows/slack-notification-pull-request-opened.yml@main
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}