name: Slack Notification - Pull Request Approved

on:
  pull_request_review:
    types:
      - submitted

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.27.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "👍  ${{ github.event.review.user.login }} approved <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} - ${{ github.event.pull_request.head.repo.full_name }}>",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "👍  *${{ github.event.review.user.login }} approved*:\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} - ${{ github.event.pull_request.head.repo.full_name }}>"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
        