name: Slack Notification - Pull Request Merged

on:
  pull_request:
    types:
      - closed

jobs:
  send_slack_message:
    if: github.event.pull_request.merged == true
    uses: gotenna/gha-workflows/.github/workflows/slack-notification-pull-request-merged.yml@main
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}